apiVersion: v1
kind: Pod
metadata:
  name: tsereda-brats-pod
  labels:
    app: fast-ddpm-brats
spec:
  securityContext:
    fsGroup: 0
  nodeSelector:
    topology.kubernetes.io/region: us-west
  containers:
    - name: brats-processing
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      env:
        - name: REPO_PATH
          value: /app/Fast-DDPM-3D-BraTS
        - name: SYNAPSE_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              name: synapse-credentials
              key: authtoken
              optional: true
        - name: PYTHONPATH
          value: /app/Fast-DDPM-3D-BraTS
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
      command:
        - "bash"
        - "-c"
      args:
        - |
          set -e  # Exit on any error
          
          echo "🚀 Starting Fast-DDPM-3D-BraTS Setup..."
          
          # Create checkpoint directory
          mkdir -p /tmp/setup_checkpoints
          
          # Update system packages
          if [ ! -f "/tmp/setup_checkpoints/packages_updated" ]; then
            echo "📦 Updating system packages..."
            sudo apt-get update && sudo apt-get install -y p7zip-full wget git vim htop
            touch /tmp/setup_checkpoints/packages_updated
          else
            echo "✓ System packages already updated"
          fi
          
          # Clone repository
          if [ ! -f "/tmp/setup_checkpoints/repo_cloned" ]; then
            echo "📂 Cloning repository..."
            if [ ! -d "${REPO_PATH}" ]; then
              git clone https://github.com/tsereda/Fast-DDPM-3D-BraTS.git ${REPO_PATH}
            fi
            touch /tmp/setup_checkpoints/repo_cloned
          else
            echo "✓ Repository already cloned"
          fi
          cd ${REPO_PATH}
          
          # Check disk usage before data extraction
          echo "📁 Current disk usage:"
          echo "  /app: $(du -sh /app 2>/dev/null || echo "N/A")"
          echo "  /data: $(du -sh /data 2>/dev/null || echo "N/A")"
          echo "  Available space: $(df -h /app | tail -1 | awk '{print $4}')"
          
          # Check for data files
          echo "📊 Checking for data files..."
          if [ -f "/data/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData.zip" ] && [ ! -f "/tmp/setup_checkpoints/training_data_extracted" ]; then
            echo "✓ Found training data"
            echo "📦 Extracting training data directly to /data (no copy)..."
            cd /data
            7z x ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData.zip -y -mmt=$(nproc) || {
              echo "⚠️ Training data extraction failed, continuing without it"
            }
            # Create symlink to avoid copying large files
            cd ${REPO_PATH}
            if [ -d "/data/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData" ]; then
              ln -sf /data/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData ./ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData
            fi
            touch /tmp/setup_checkpoints/training_data_extracted
          elif [ -f "/tmp/setup_checkpoints/training_data_extracted" ]; then
            echo "✓ Training data already extracted"
            cd ${REPO_PATH}
            # Ensure symlink exists
            if [ -d "/data/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData" ] && [ ! -e "./ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData" ]; then
              ln -sf /data/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData ./ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData
            fi
          else
            echo "⚠️ Training data not found in /data/"
          fi
          
          if [ -f "/data/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData.zip" ] && [ ! -f "/tmp/setup_checkpoints/validation_data_extracted" ]; then
            echo "✓ Found validation data"
            echo "📦 Extracting validation data directly to /data (no copy)..."
            cd /data
            7z x ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData.zip -y -mmt=$(nproc) || {
              echo "⚠️ Validation data extraction failed, continuing without it"
            }
            # Create symlink to avoid copying large files
            cd ${REPO_PATH}
            if [ -d "/data/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData" ]; then
              ln -sf /data/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData ./ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData
            fi
            touch /tmp/setup_checkpoints/validation_data_extracted
          elif [ -f "/tmp/setup_checkpoints/validation_data_extracted" ]; then
            echo "✓ Validation data already extracted"
            cd ${REPO_PATH}
            # Ensure symlink exists
            if [ -d "/data/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData" ] && [ ! -e "./ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData" ]; then
              ln -sf /data/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData ./ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData
            fi
          else
            echo "⚠️ Validation data not found in /data/"
          fi
          
          # Setup environment
          if [ ! -f "/tmp/setup_checkpoints/environment_setup" ]; then
            echo "🐍 Setting up Python environment..."
            cd ${REPO_PATH}
            
            # Add error handling for container runtime issues
            echo "🔍 Checking container runtime..."
            if ! command -v conda &> /dev/null; then
              echo "❌ Conda not found, installing miniconda..."
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              bash miniconda.sh -b -p /opt/miniconda
              export PATH="/opt/miniconda/bin:$PATH"
              rm miniconda.sh
            fi
            
            # Initialize conda with retry mechanism
            echo "🔄 Initializing conda..."
            for i in {1..3}; do
              if eval "$(conda shell.bash hook)" 2>/dev/null; then
                echo "✓ Conda initialized successfully"
                break
              else
                echo "⚠️ Conda initialization attempt $i failed, retrying..."
                sleep 5
              fi
            done
            
            # Check if environment exists with retry
            echo "🔍 Checking for existing environment..."
            if conda env list | grep -q "brasyn" 2>/dev/null; then
              echo "✓ Environment brasyn already exists, activating..."
              conda activate brasyn || {
                echo "⚠️ Failed to activate existing environment, recreating..."
                conda env remove -n brasyn -y 2>/dev/null || true
              }
            fi
            
            # Create environment if it doesn't exist or activation failed
            if ! conda env list | grep -q "brasyn" 2>/dev/null; then
              echo "🔧 Creating brasyn environment..."
              if [ -f "environment.yml" ]; then
                # Try with mamba first, fall back to conda
                if command -v mamba &> /dev/null; then
                  echo "Using mamba for faster installation..."
                  timeout 900 mamba env create -f environment.yml -y || {
                    echo "⚠️ Mamba failed or timed out, trying conda..."
                    timeout 1200 conda env create -f environment.yml -y || {
                      echo "❌ Environment creation failed, creating minimal environment..."
                      conda create -n brasyn python=3.11 -y
                    }
                  }
                else
                  echo "Using conda for environment creation..."
                  timeout 1200 conda env create -f environment.yml -y || {
                    echo "❌ Environment creation failed, creating minimal environment..."
                    conda create -n brasyn python=3.11 -y
                  }
                fi
              else
                echo "⚠️ environment.yml not found, creating minimal environment..."
                conda create -n brasyn python=3.11 -y
              fi
              
              # Activate the newly created environment
              conda activate brasyn || {
                echo "❌ Failed to activate environment, using base environment"
                export CONDA_DEFAULT_ENV=base
              }
            fi
              
            # Install essential packages with retries
            echo "📦 Installing essential packages..."
            for package_group in \
              "torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118" \
              "numpy nibabel SimpleITK tqdm PyYAML matplotlib scipy pandas" \
              "opencv-python scikit-image gdown wandb lpips einops accelerate"; do
              
              echo "Installing: $package_group"
              for attempt in {1..3}; do
                if pip install $package_group --no-cache-dir; then
                  echo "✓ Successfully installed: $package_group"
                  break
                else
                  echo "⚠️ Attempt $attempt failed for: $package_group"
                  if [ $attempt -eq 3 ]; then
                    echo "❌ Failed to install: $package_group (continuing anyway)"
                  else
                    sleep 10
                  fi
                fi
              done
            done
            
            touch /tmp/setup_checkpoints/environment_setup
          else
            echo "✓ Python environment already set up"
            cd ${REPO_PATH}
            eval "$(conda shell.bash hook)" 2>/dev/null || true
            conda activate brasyn 2>/dev/null || true
          fi
          
          # Verify environment and system health
          echo "🔍 Verifying environment and system health..."
          echo "💾 Memory usage: $(free -h | grep Mem)"
          echo "💻 CPU usage: $(top -bn1 | grep "Cpu(s)" | awk '{print $2}')"
          echo "🖥️  GPU info:"
          nvidia-smi --query-gpu=name,memory.total,memory.used --format=csv,noheader,nounits 2>/dev/null || echo "⚠️ GPU info not available"
          
          # Test Python environment
          python -c "import sys; print(f'Python: {sys.version}'); import torch; print(f'PyTorch: {torch.__version__}'); print(f'CUDA available: {torch.cuda.is_available()}'); print(f'GPU count: {torch.cuda.device_count()}') if torch.cuda.is_available() else None" 2>/dev/null || echo "⚠️ Python environment check failed"
          
          # Run basic tests
          echo "🧪 Running basic tests..."
          if [ -f "test_comprehensive.py" ]; then
            python test_comprehensive.py || echo "⚠️ Some tests failed, continuing..."
          fi
          
          if [ -f "test_3d_model.py" ]; then
            python test_3d_model.py || echo "⚠️ 3D model test failed, continuing..."
          fi
          
          # Quick fixes if needed
          if [ -f "quick_fixes.py" ]; then
            echo "🔧 Applying quick fixes..."
            python quick_fixes.py || echo "⚠️ Quick fixes failed, continuing..."
          fi
          
          # Setup nnUNet directories if needed
          export nnUNet_raw="/app/nnunet/raw"
          export nnUNet_preprocessed="/app/nnunet/preprocessed" 
          export nnUNet_results="/app/nnunet/results"
          mkdir -p /app/nnunet/{raw,preprocessed,results}
          
          # Convert data to nnUNet format if script exists
          if [ -f "Dataset137_BraTS21.py" ] && [ -d "ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData" ]; then
            echo "🔄 Converting data to nnUNet format..."
            python Dataset137_BraTS21.py || echo "⚠️ Data conversion failed, continuing..."
          fi
          
          echo "✅ Setup complete!"
          echo "📋 Available commands:"
          echo "  - Training: python scripts/train_3d.py --data_root ./ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData --debug"
          echo "  - Training (alt): python scripts/train_3d.py --data_root /data/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData --debug"
          echo "  - Inference: python scripts/inference_3d.py --help"
          echo "  - Environment check: python verify_environment.py"
          echo ""
          echo "📁 Data locations:"
          echo "  - Training data: /data/ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData"
          echo "  - Validation data: /data/ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData"
          echo "  - Symlinks in repo: $(ls -la ${REPO_PATH}/ | grep ^l || echo 'None')"
          echo ""
          echo "🖥️  Container will stay alive. Connect with:"
          echo "    kubectl exec -it tsereda-brats-pod -- /bin/bash"
          echo ""
          echo "📊 Final system status:"
          echo "💾 Memory: $(free -h | grep Mem | awk '{print $3"/"$2}')"
          echo "💻 Load: $(uptime | awk -F'load average:' '{print $2}')"
          echo "📁 Disk usage: $(df -h /app | tail -1 | awk '{print $3"/"$2" ("$5")"}')"
          
          # Mark setup as complete for readiness probe
          touch /tmp/setup_complete
          
          # Keep container running
          tail -f /dev/null
      volumeMounts:
        - name: git-repo
          mountPath: /app
        - name: brats-data-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      resources:
        limits:
          memory: 32Gi
          cpu: "16"
          nvidia.com/gpu: "1"
        requests:
          memory: 24Gi
          cpu: "12"
          nvidia.com/gpu: "1"
      securityContext:
        runAsUser: 0
        capabilities:
          add:
            - SYS_NICE
            - IPC_LOCK
      # Add liveness and readiness probes for better pod management
      livenessProbe:
        exec:
          command:
            - /bin/bash
            - -c
            - "ps aux | grep -v grep | grep -q tail || exit 1"
        initialDelaySeconds: 300
        periodSeconds: 60
        timeoutSeconds: 10
        failureThreshold: 3
      readinessProbe:
        exec:
          command:
            - /bin/bash
            - -c
            - "test -f /tmp/setup_complete"
        initialDelaySeconds: 60
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 10
  volumes:
    - name: git-repo
      emptyDir:
        sizeLimit: 50Gi  # Increased from 20Gi to handle any temporary files
    - name: brats-data-volume
      persistentVolumeClaim:
        claimName: brats2025-1
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
  restartPolicy: Never
  terminationGracePeriodSeconds: 30