apiVersion: v1
kind: Pod
metadata:
  name: tsereda-brats-pod
  labels:
    app: fast-ddpm-brats
spec:
  nodeSelector:
    topology.kubernetes.io/region: us-west
  
  containers:
    - name: brats-processing
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      
      env:
        - name: REPO_PATH
          value: /app/Fast-DDPM-3D-BraTS
        - name: PYTHONPATH
          value: /app/Fast-DDPM-3D-BraTS
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        # nnUNet paths
        - name: nnUNet_raw
          value: /app/nnunet/raw
        - name: nnUNet_preprocessed
          value: /app/nnunet/preprocessed
        - name: nnUNet_results
          value: /app/nnunet/results
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8"
      
      command: ["/bin/bash", "-c"]
      args:
        - |
          # Clone repository
          git clone https://github.com/tsereda/Fast-DDPM-3D-BraTS.git ${REPO_PATH}
          cd ${REPO_PATH}
          
          # Create directories
          mkdir -p /app/nnunet/{raw,preprocessed,results}
          
          # Install dependencies
          apt-get update && apt-get install -y p7zip-full wget git
          
          # Extract datasets if available
          for dataset in "TrainingData" "ValidationData"; do
            zip_file="/data/ASNR-MICCAI-BraTS2023-GLI-Challenge-${dataset}.zip"
            if [ -f "$zip_file" ]; then
              echo "Extracting ${dataset}..."
              cd /data && 7z x "$zip_file" -y
              cd ${REPO_PATH}
              ln -sf "/data/ASNR-MICCAI-BraTS2023-GLI-Challenge-${dataset}" .
            fi
          done
          
          pip install pyyaml
          pip install torch
          pip install tqdm
          pip install numpy
          pip install nibabel
          python scripts/train_3d.py --data_root ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData 2>&1 | tee -a /app/training.log
          
          # Keep pod running
          tail -f /dev/null
      
      volumeMounts:
        - name: workspace
          mountPath: /app
        - name: data
          mountPath: /data
        - name: shm
          mountPath: /dev/shm
      
      resources:
        requests:
          memory: 28Gi
          cpu: "12"
          nvidia.com/gpu: "1"
        limits:
          memory: 32Gi
          cpu: "16"
          nvidia.com/gpu: "1"
  
  volumes:
    - name: workspace
      emptyDir:
        sizeLimit: 50Gi
    - name: data
      persistentVolumeClaim:
        claimName: brats2025-1
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
  
  restartPolicy: Never